
// kuldes
// UDP message to 255.255.255.255:1234): TOTORO discovery_port_number

/*

    IP is automatically generated by the DHCP server
    port can be a custom number
    this socket receives the discovery request answers from other users
*/
